/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-29 13:46:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Works/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Umobile2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1730814071403L));
    _jspx_dependants.put("/WEB-INF/views/includes/header.jsp", Long.valueOf(1732887557767L));
    _jspx_dependants.put("/WEB-INF/views/includes/subfooter.jsp", Long.valueOf(1732776122718L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/csss/memberlogin.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/csss/subindex.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 로그인 작업완료 -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"header\">\r\n");
      out.write("		<div class=\"logbox\">\r\n");
      out.write("			<a href=\"/\"> <img class=\"logimg\"\r\n");
      out.write("				src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/headerlogo.png\">\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-10\">\r\n");
      out.write("			<ul class=\"lower-navbar\">\r\n");
      out.write("				<li><a href=\"\">유심/eSIM</a></li>\r\n");
      out.write("				<li><a href=\"#\" id=\"toggleLink\">휴대폰</a></li>\r\n");
      out.write("				<li><a href=\"\">상품</a></li>\r\n");
      out.write("				<li><a href=\"#\">이벤트/혜택</a></li>\r\n");
      out.write("				<li><a href=\"/user/notice\">공지사항</a></li>\r\n");
      out.write("				<li><a href=\"#\" id=\"toggleLink-1\">내 정보</a></li>\r\n");
      out.write("				<li><a href=\"#\">유모바일</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div class=\"submenu\">\r\n");
      out.write("				<div class=\"submenus\">\r\n");
      out.write("					<div class=\"submenuimg\">\r\n");
      out.write("						<a href=\"#\"><img\r\n");
      out.write("							src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/img-gnb-lo.png\"></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<ul class=\"submeul\">\r\n");
      out.write("						<li class=\"submeli\"><a href=\"/phone/phoneproduct\">가입신청</a></li>\r\n");
      out.write("						<li class=\"submeli\"><a href=\"#\">모델별 지원금</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"submenus\">\r\n");
      out.write("					<div class=\"submenuimg\">\r\n");
      out.write("						<a href=\"#\"><img\r\n");
      out.write("							src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/img-gnb-lo1.png\"></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<ul class=\"submeul\">\r\n");
      out.write("						<li class=\"submeli\"><a href=\"#\">가입신청</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 내 정보 서브 메뉴 시작  -->\r\n");
      out.write("			<div class=\"submenu-1\">\r\n");
      out.write("				<div class=\"submenus-1\">\r\n");
      out.write("					<ul class=\"submeul-1\">\r\n");
      out.write("						<li class=\"submeli-1\"><a href=\"/user/checkdetails\"\r\n");
      out.write("							onclick=\"return checkLoginBeforeRedirect()\">신청 내역</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"submenus-1\">\r\n");
      out.write("					<ul class=\"submeul-1\">\r\n");
      out.write("						<li class=\"submeli-1\"><a href=\"/user/Edit\"\r\n");
      out.write("							onclick=\"return checkLoginBeforeRedirect()\">정보 수정</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 내 정보 서브 메뉴  끝 -->\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"top-util\">\r\n");
      out.write("			<div class=\"navlog\">\r\n");
      out.write("				<a href=\"#\"> <img class=\"navimg\"\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/navlog1.png\">\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"navlog\">\r\n");
      out.write("				<a href=\"#\"> <img class=\"navimg\"\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/navlog2.png\">\r\n");
      out.write("					<b class=\"state\" id=\"toggle\" style=\"display: none;\">ON</b> <!-- 로그인 후 상태 -->\r\n");
      out.write("				</a>\r\n");
      out.write("				<!--  로그인 전에만 보이는 부분 -->\r\n");
      out.write("				<div class=\"navsub\" style=\"display: none;\">\r\n");
      out.write("					<div class=\"info-basic\">\r\n");
      out.write("						<button type=\"button\" id=\"btns\" class=\"top-login\"\r\n");
      out.write("							onclick=\"window.location.href = '/user/login';\">로그인</button>\r\n");
      out.write("						<ul class=\"find-join\">\r\n");
      out.write("							<li><a href=\"#\">ID/비밀번호찾기</a></li>\r\n");
      out.write("							<li><a href=\"/user/join\">회원가입</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info-func\">\r\n");
      out.write("						<div class=\"func-btn\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<img\r\n");
      out.write("									src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/log-doc.svg\">\r\n");
      out.write("								<li><a href=\"/user/checkdetails\" onclick=\"return checkLoginBeforeRedirect()\">신청내역조회</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 로그인 후에만 보이는 부분  -->\r\n");
      out.write("				<div class=\"loginboxs\">\r\n");
      out.write("					<strong class=\"info-user\"> <name id=\"gnbMmbrNm\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</name>\r\n");
      out.write("						님 <a href=\"/user/Edit\" class=\"member-modify\">회원정보수정</a>\r\n");
      out.write("					</strong>\r\n");
      out.write("					<div class=\"info-func\">\r\n");
      out.write("						<ul class=\"func-btn\">\r\n");
      out.write("							<li><a href=\"/user/checkdetails\" class=\"member-modify2\">신청내역\r\n");
      out.write("									조회</a></li>\r\n");
      out.write("							<li class=\"btnSBMB\"><a href=\"/phone/comparison\"\r\n");
      out.write("								class=\"btn-num-auth\">견적 비교하기</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"guide-box pint-bx\">\r\n");
      out.write("							<a href=\"#\">\r\n");
      out.write("								<p>\r\n");
      out.write("									<strong>포인트</strong> <span id=\"gnbPoint\">0P</span>\r\n");
      out.write("								</p>\r\n");
      out.write("							</a> <a href=\"#\">\r\n");
      out.write("								<p id=\"ucashArea2\">\r\n");
      out.write("									<strong>U폰 캐시</strong> <span id=\"gnbUcash\">0C</span>\r\n");
      out.write("								</p>\r\n");
      out.write("							</a>\r\n");
      out.write("							<p class=\"fir\">친구추천하고 특별한 혜택을 받으세요</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"devcechg-txt\">기기변경 상담 1661-0556 (유료)</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"logbox-btm\">\r\n");
      out.write("						<a href=\"/logout\">\r\n");
      out.write("							<button class=\"btn-text-right-s btn-logout\">로그아웃</button>\r\n");
      out.write("						</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"navlog\">\r\n");
      out.write("				<a href=\"#\"> <img class=\"navimg\"\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/navlog3.png\">\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 헤더 끝 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script>\r\n");
      out.write("<!--메뉴 펼침 -->\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    let isSubmenuVisible = false; // .submenu 표시 상태 변수\r\n");
      out.write("\r\n");
      out.write("    $('#toggleLink').click(function() {\r\n");
      out.write("        isSubmenuVisible = !isSubmenuVisible; // 상태 토글\r\n");
      out.write("        if (isSubmenuVisible) {\r\n");
      out.write("            $('.submenu').show(); // 표시\r\n");
      out.write("        } else {\r\n");
      out.write("            $('.submenu').hide(); // 숨김\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" $(document).ready(function() {\r\n");
      out.write("    let isSubmenuVisible = false; // .submenu 표시 상태 변수\r\n");
      out.write("\r\n");
      out.write("    $('#toggleLink-1').click(function() {\r\n");
      out.write("        isSubmenuVisible = !isSubmenuVisible; // 상태 토글\r\n");
      out.write("        if (isSubmenuVisible) {\r\n");
      out.write("            $('.submenu-1').show(); // 표시\r\n");
      out.write("        } else {\r\n");
      out.write("            $('.submenu-1').hide(); // 숨김\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}); \r\n");
      out.write("\r\n");
      out.write("<!--메뉴 펼침 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 모달 -->\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("	\r\n");
      out.write("    $('#toggle').click(function () {\r\n");
      out.write("        if ($('.state').is(':visible')) {\r\n");
      out.write("            // 로그인 후 상태: .state가 보이는 경우\r\n");
      out.write("            $('.loginboxs').toggle(); // 로그인 박스 토글\r\n");
      out.write("        } else {\r\n");
      out.write("            // 로그인 전 상태: .state가 보이지 않는 경우\r\n");
      out.write("            $('.navsub').toggle(); // 네비게이션 메뉴 토글\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 모달 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 로그인 전, 후 보여주는   */\r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("  const navSub = document.querySelector(\".navsub\");\r\n");
      out.write("  const loginBox = document.querySelector(\".loginboxs\");\r\n");
      out.write("  const navImg = document.querySelector(\".navlog > a\");\r\n");
      out.write("  const session = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("  const toggle = document.querySelector(\"#toggle\");\r\n");
      out.write("\r\n");
      out.write("  if (session !== null && session !== \"\") {\r\n");
      out.write("    // 로그인 상태일 경우\r\n");
      out.write("    navSub.style.display = \"none\";\r\n");
      out.write("    loginBox.style.display = \"block\";\r\n");
      out.write("    navImg.style.display = \"block\";\r\n");
      out.write("    toggle.style.display = \"block\";\r\n");
      out.write("  } else {\r\n");
      out.write("    // 비로그인 상태일 경우\r\n");
      out.write("    navSub.style.display = \"block\";\r\n");
      out.write("    loginBox.style.display = \"none\";\r\n");
      out.write("    navImg.style.display = \"none\";\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//로그인체크\r\n");
      out.write("function checkLoginBeforeRedirect() {\r\n");
      out.write("	  var isUserLoggedIn = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("	  if (!isUserLoggedIn) {\r\n");
      out.write("            alert(\"로그인 후 이용 가능한 서비스입니다.\");\r\n");
      out.write("            return false;  // 페이지 이동을 막음\r\n");
      out.write("        } else {\r\n");
      out.write("            return true;  // 로그인된 상태라면 페이지 이동 허용\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div id=\"login-warp\">\r\n");
      out.write("		<div class=\"sub-conts login util-width login-info\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"page-tit\">\r\n");
      out.write("				<h1>로그인</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"rq-form\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"main-txt-group\">\r\n");
      out.write("					<h2 class=\"main-txt\">가입한 아이디와 비밀번호를 확인해주세요.</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<form action=\"login\" method=\"post\" onsubmit=\"return checkStuff()\">\r\n");
      out.write("					<div id=\"divid\" class=\"box-input\">\r\n");
      out.write("						<div class=\"input-wrap\">\r\n");
      out.write("							<input id=\"email\" type=\"text\" name=\"username\"\r\n");
      out.write("								placeholder=\"이메일(아이디)를 입력해주세요\" class=\"input-default is-delete\"\r\n");
      out.write("								title=\"email\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"input-wrap\">\r\n");
      out.write("							<input id=\"password\" type=\"password\" name=\"password\"\r\n");
      out.write("								placeholder=\"비밀번호 를 입력하세요\" class=\"input-default is-delete\"\r\n");
      out.write("								title=\"password\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button class=\"btns wid md-ripples ripples-light\" type=\"submit\"\r\n");
      out.write("						onclick=\"\">로그인</button>\r\n");
      out.write("				</form>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/csss/subindex.css\" rel=\"stylesheet\"/> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--  footer 시작 -->\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"subfooter\">\r\n");
      out.write("     <div class=\"subfooter-top\">\r\n");
      out.write("        <div class=\"wrqp\">\r\n");
      out.write("            <ul class=\"subf-menu\">\r\n");
      out.write("               <li>\r\n");
      out.write("                 <a href=\"#\">회사소개</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                 <a href=\"#\">제휴문의</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                 <a href=\"#\">법인가입 문의</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                 <a href=\"#\">이용약관</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                 <a href=\"#\">위치기반서비스이용약관</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                <li class=\"stro\">\r\n");
      out.write("                 <a href=\"#\">개인정보처리방침</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                 <a href=\"#\">이메일무단수집거부</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                 <a href=\"#\">명의도용방지서비스</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                 <a href=\"#\">불법스팸대응센터</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                 <a href=\"#\">이용자 피해예방</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                 <a href=\"#\">서비스 이용가능 지역</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                <li class=\"stro\">\r\n");
      out.write("                 <a href=\"/admin/adminloginJoin\">관리자 로그인</a>\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("     <div class=\"subfooter-bottom\">\r\n");
      out.write("        <div class=\"subfooter-mid\">\r\n");
      out.write("            <div class=\"subaddress\">\r\n");
      out.write("              <div class=\"orn\">\r\n");
      out.write("                 <a href=\"#\">(주)미디어로그</a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <p>서울특별시 마포구 월드컵북로 416(상암동) LG유플러스</p>\r\n");
      out.write("              <p>\r\n");
      out.write("               <span>대표이사 : 이상헌</span>\r\n");
      out.write("               <span>사업자등록번호 : 114-81-96221</span>\r\n");
      out.write("              </p>\r\n");
      out.write("              <p>통신판매신고 : 제2012-서울마포-0954호</p>\r\n");
      out.write("              <p class=\"copyright\">COPYRIGHT © MEDIALOG CORP. ALL RIGHTS RESERVED</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"subf-info\">\r\n");
      out.write("               <dl>\r\n");
      out.write("                 <dt>개통센터</dt>\r\n");
      out.write("                 <dd>\r\n");
      out.write("                   <p class=\"tel\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                     신청/배송/개통문의 1661-0544 (유료)\r\n");
      out.write("                     <br>\r\n");
      out.write("                     기기변경문의 1661-0556 (유료)\r\n");
      out.write("                    </span>\r\n");
      out.write("                   </p>\r\n");
      out.write("                   <p>\r\n");
      out.write("                   운영시간 : 평일 09시~20시\r\n");
      out.write("                   <br>\r\n");
      out.write("                   (점심시간: 12시 30분~13시 30분)\r\n");
      out.write("                   <br>\r\n");
      out.write("                   1644-2106 (For Foreigners)\r\n");
      out.write("                   </p>\r\n");
      out.write("                 </dd>\r\n");
      out.write("               </dl>\r\n");
      out.write("               <dl>\r\n");
      out.write("                 <dt>고객센터</dt>\r\n");
      out.write("                 <dd>\r\n");
      out.write("                   <p class=\"tel\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                     114(자사 휴대폰 무료)\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span>\r\n");
      out.write("                    1644-5353(유료)\r\n");
      out.write("                    </span>\r\n");
      out.write("                   </p>\r\n");
      out.write("                   <p>\r\n");
      out.write("                   운영시간 : 평일 09시~18시 \r\n");
      out.write("                   <br>\r\n");
      out.write("                   (점심시간 12시~13시)\r\n");
      out.write("                   </p>\r\n");
      out.write("                 </dd>\r\n");
      out.write("               </dl>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!--  footer 끝 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 서버에서 전달된 메시지 표시 -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/user/login.jsp(54,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginMessage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("		<script>\r\n");
        out.write("			alert('");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("');\r\n");
        out.write("		</script>\r\n");
        out.write("	");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager());
    return false;
  }
}
